export const countriesList = [
    { englishName: "Afghanistan", frenchName: "Afghanistan" },
    { englishName: "Albania", frenchName: "Albanie" },
    { englishName: "Algeria", frenchName: "Algérie" },
    { englishName: "Andorra", frenchName: "Andorre" },
    { englishName: "Angola", frenchName: "Angola" },
    { englishName: "Antigua and Barbuda", frenchName: "Antigua-et-Barbuda" },
    { englishName: "Argentina", frenchName: "Argentine" },
    { englishName: "Armenia", frenchName: "Arménie" },
    { englishName: "Australia", frenchName: "Australie" },
    { englishName: "Austria", frenchName: "Autriche" },
    { englishName: "Azerbaijan", frenchName: "Azerbaïdjan" },
    { englishName: "Bahamas", frenchName: "Bahamas" },
    { englishName: "Bahrain", frenchName: "Bahreïn" },
    { englishName: "Bangladesh", frenchName: "Bangladesh" },
    { englishName: "Barbados", frenchName: "Barbade" },
    { englishName: "Belarus", frenchName: "Biélorussie" },
    { englishName: "Belgium", frenchName: "Belgique" },
    { englishName: "Belize", frenchName: "Belize" },
    { englishName: "Benin", frenchName: "Bénin" },
    { englishName: "Bhutan", frenchName: "Bhoutan" },
    { englishName: "Bolivia", frenchName: "Bolivie" },
    { englishName: "Bosnia and Herzegovina", frenchName: "Bosnie-Herzégovine" },
    { englishName: "Botswana", frenchName: "Botswana" },
    { englishName: "Brazil", frenchName: "Brésil" },
    { englishName: "Brunei", frenchName: "Brunei" },
    { englishName: "Bulgaria", frenchName: "Bulgarie" },
    { englishName: "Burkina Faso", frenchName: "Burkina Faso" },
    { englishName: "Burundi", frenchName: "Burundi" },
    { englishName: "Cabo Verde", frenchName: "Cap-Vert" },
    { englishName: "Cambodia", frenchName: "Cambodge" },
    { englishName: "Cameroon", frenchName: "Cameroun" },
    { englishName: "Canada", frenchName: "Canada" },
    { englishName: "Central African Republic", frenchName: "République centrafricaine" },
    { englishName: "Chad", frenchName: "Tchad" },
    { englishName: "Chile", frenchName: "Chili" },
    { englishName: "China", frenchName: "Chine" },
    { englishName: "Colombia", frenchName: "Colombie" },
    { englishName: "Comoros", frenchName: "Comores" },
    { englishName: "Congo (Congo-Brazzaville)", frenchName: "Congo (Congo-Brazzaville)" },
    { englishName: "Costa Rica", frenchName: "Costa Rica" },
    { englishName: "Croatia", frenchName: "Croatie" },
    { englishName: "Cuba", frenchName: "Cuba" },
    { englishName: "Cyprus", frenchName: "Chypre" },
    { englishName: "Czech Republic", frenchName: "République tchèque" },
    { englishName: "Denmark", frenchName: "Danemark" },
    { englishName: "Djibouti", frenchName: "Djibouti" },
    { englishName: "Dominica", frenchName: "Dominique" },
    { englishName: "Dominican Republic", frenchName: "République dominicaine" },
    { englishName: "Ecuador", frenchName: "Équateur" },
    { englishName: "Egypt", frenchName: "Égypte" },
    { englishName: "El Salvador", frenchName: "Salvador" },
    { englishName: "Equatorial Guinea", frenchName: "Guinée équatoriale" },
    { englishName: "Eritrea", frenchName: "Érythrée" },
    { englishName: "Estonia", frenchName: "Estonie" },
    { englishName: "Eswatini", frenchName: "Eswatini" },
    { englishName: "Ethiopia", frenchName: "Éthiopie" },
    { englishName: "Fiji", frenchName: "Fidji" },
    { englishName: "Finland", frenchName: "Finlande" },
    { englishName: "France", frenchName: "France" },
    { englishName: "Gabon", frenchName: "Gabon" },
    { englishName: "Gambia", frenchName: "Gambie" },
    { englishName: "Georgia", frenchName: "Géorgie" },
    { englishName: "Germany", frenchName: "Allemagne" },
    { englishName: "Ghana", frenchName: "Ghana" },
    { englishName: "Greece", frenchName: "Grèce" },
    { englishName: "Grenada", frenchName: "Grenade" },
    { englishName: "Guatemala", frenchName: "Guatemala" },
    { englishName: "Guinea", frenchName: "Guinée" },
    { englishName: "Guinea-Bissau", frenchName: "Guinée-Bissau" },
    { englishName: "Guyana", frenchName: "Guyana" },
    { englishName: "Haiti", frenchName: "Haïti" },
    { englishName: "Honduras", frenchName: "Honduras" },
    { englishName: "Hungary", frenchName: "Hongrie" },
    { englishName: "Iceland", frenchName: "Islande" },
    { englishName: "India", frenchName: "Inde" },
    { englishName: "Indonesia", frenchName: "Indonésie" },
    { englishName: "Iran", frenchName: "Iran" },
    { englishName: "Iraq", frenchName: "Irak" },
    { englishName: "Ireland", frenchName: "Irlande" },
    { englishName: "Israel", frenchName: "Israël" },
    { englishName: "Italy", frenchName: "Italie" },
    { englishName: "Jamaica", frenchName: "Jamaïque" },
    { englishName: "Japan", frenchName: "Japon" },
    { englishName: "Jordan", frenchName: "Jordanie" },
    { englishName: "Kazakhstan", frenchName: "Kazakhstan" },
    { englishName: "Kenya", frenchName: "Kenya" },
    { englishName: "Kiribati", frenchName: "Kiribati" },
    { englishName: "Kuwait", frenchName: "Koweït" },
    { englishName: "Kyrgyzstan", frenchName: "Kirghizistan" },
    { englishName: "Laos", frenchName: "Laos" },
    { englishName: "Latvia", frenchName: "Lettonie" },
    { englishName: "Lebanon", frenchName: "Liban" },
    { englishName: "Lesotho", frenchName: "Lesotho" },
    { englishName: "Liberia", frenchName: "Libéria" },
    { englishName: "Libya", frenchName: "Libye" },
    { englishName: "Liechtenstein", frenchName: "Liechtenstein" },
    { englishName: "Lithuania", frenchName: "Lituanie" },
    { englishName: "Luxembourg", frenchName: "Luxembourg" },
    { englishName: "Madagascar", frenchName: "Madagascar" },
    { englishName: "Malawi", frenchName: "Malawi" },
    { englishName: "Malaysia", frenchName: "Malaisie" },
    { englishName: "Maldives", frenchName: "Maldives" },
    { englishName: "Mali", frenchName: "Mali" },
    { englishName: "Malta", frenchName: "Malte" },
    { englishName: "Marshall Islands", frenchName: "Îles Marshall" },
    { englishName: "Mauritania", frenchName: "Mauritanie" },
    { englishName: "Mauritius", frenchName: "Maurice" },
    { englishName: "Mexico", frenchName: "Mexique" },
    { englishName: "Micronesia", frenchName: "Micronésie" },
    { englishName: "Moldova", frenchName: "Moldavie" },
    { englishName: "Monaco", frenchName: "Monaco" },
    { englishName: "Mongolia", frenchName: "Mongolie" },
    { englishName: "Montenegro", frenchName: "Monténégro" },
    { englishName: "Morocco", frenchName: "Maroc" },
    { englishName: "Mozambique", frenchName: "Mozambique" },
    { englishName: "Myanmar (Burma)", frenchName: "Myanmar (Birmanie)" },
    { englishName: "Namibia", frenchName: "Namibie" },
    { englishName: "Nauru", frenchName: "Nauru" },
    { englishName: "Nepal", frenchName: "Népal" },
    { englishName: "Netherlands", frenchName: "Pays-Bas" },
    { englishName: "New Zealand", frenchName: "Nouvelle-Zélande" },
    { englishName: "Nicaragua", frenchName: "Nicaragua" },
    { englishName: "Niger", frenchName: "Niger" },
    { englishName: "Nigeria", frenchName: "Nigéria" },
    { englishName: "North Korea", frenchName: "Corée du Nord" },
    { englishName: "North Macedonia", frenchName: "Macédoine du Nord" },
    { englishName: "Norway", frenchName: "Norvège" },
    { englishName: "Oman", frenchName: "Oman" },
    { englishName: "Pakistan", frenchName: "Pakistan" },
    { englishName: "Palau", frenchName: "Palaos" },
    { englishName: "Palestine State", frenchName: "État de Palestine" },
    { englishName: "Panama", frenchName: "Panama" },
    { englishName: "Papua New Guinea", frenchName: "Papouasie-Nouvelle-Guinée" },
    { englishName: "Paraguay", frenchName: "Paraguay" },
    { englishName: "Peru", frenchName: "Pérou" },
    { englishName: "Philippines", frenchName: "Philippines" },
    { englishName: "Poland", frenchName: "Pologne" },
    { englishName: "Portugal", frenchName: "Portugal" },
    { englishName: "Qatar", frenchName: "Qatar" },
    { englishName: "Romania", frenchName: "Roumanie" },
    { englishName: "Russia", frenchName: "Russie" },
    { englishName: "Rwanda", frenchName: "Rwanda" },
    { englishName: "Saint Kitts and Nevis", frenchName: "Saint-Christophe-et-Niévès" },
    { englishName: "Saint Lucia", frenchName: "Sainte-Lucie" },
    { englishName: "Saint Vincent and the Grenadines", frenchName: "Saint-Vincent-et-les-Grenadines" },
    { englishName: "Samoa", frenchName: "Samoa" },
    { englishName: "San Marino", frenchName: "Saint-Marin" },
    { englishName: "Sao Tome and Principe", frenchName: "Sao Tomé-et-Principe" },
    { englishName: "Saudi Arabia", frenchName: "Arabie saoudite" },
    { englishName: "Senegal", frenchName: "Sénégal" },
    { englishName: "Serbia", frenchName: "Serbie" },
    { englishName: "Seychelles", frenchName: "Seychelles" },
    { englishName: "Sierra Leone", frenchName: "Sierra Leone" },
    { englishName: "Singapore", frenchName: "Singapour" },
    { englishName: "Slovakia", frenchName: "Slovaquie" },
    { englishName: "Slovenia", frenchName: "Slovénie" },
    { englishName: "Solomon Islands", frenchName: "Îles Salomon" },
    { englishName: "Somalia", frenchName: "Somalie" },
    { englishName: "South Africa", frenchName: "Afrique du Sud" },
    { englishName: "South Korea", frenchName: "Corée du Sud" },
    { englishName: "South Sudan", frenchName: "Soudan du Sud" },
    { englishName: "Spain", frenchName: "Espagne" },
    { englishName: "Sri Lanka", frenchName: "Sri Lanka" },
    { englishName: "Sudan", frenchName: "Soudan" },
    { englishName: "Suriname", frenchName: "Suriname" },
    { englishName: "Sweden", frenchName: "Suède" },
    { englishName: "Switzerland", frenchName: "Suisse" },
    { englishName: "Syria", frenchName: "Syrie" },
    { englishName: "Taiwan", frenchName: "Taïwan" },
    { englishName: "Tajikistan", frenchName: "Tadjikistan" },
    { englishName: "Tanzania", frenchName: "Tanzanie" },
    { englishName: "Thailand", frenchName: "Thaïlande" },
    { englishName: "Timor-Leste", frenchName: "Timor-Leste" },
    { englishName: "Togo", frenchName: "Togo" },
    { englishName: "Tonga", frenchName: "Tonga" },
    { englishName: "Trinidad and Tobago", frenchName: "Trinité-et-Tobago" },
    { englishName: "Tunisia", frenchName: "Tunisie" },
    { englishName: "Turkey", frenchName: "Turquie" },
    { englishName: "Turkmenistan", frenchName: "Turkménistan" },
    { englishName: "Tuvalu", frenchName: "Tuvalu" },
    { englishName: "Uganda", frenchName: "Ouganda" },
    { englishName: "Ukraine", frenchName: "Ukraine" },
    { englishName: "United Arab Emirates", frenchName: "Émirats arabes unis" },
    { englishName: "United Kingdom", frenchName: "Royaume-Uni" },
    { englishName: "United States of America", frenchName: "États-Unis" },
    { englishName: "Uruguay", frenchName: "Uruguay" },
    { englishName: "Uzbekistan", frenchName: "Ouzbékistan" },
    { englishName: "Vanuatu", frenchName: "Vanuatu" },
    { englishName: "Vatican City", frenchName: "Vatican" },
    { englishName: "Venezuela", frenchName: "Venezuela" },
    { englishName: "Vietnam", frenchName: "Viêt Nam" },
    { englishName: "Yemen", frenchName: "Yémen" },
    { englishName: "Zambia", frenchName: "Zambie" },
    { englishName: "Zimbabwe", frenchName: "Zimbabwe" }
];


export const countryNameInFrench = (countryName) => {
    const  country = countriesList.find(country => country.englishName === countryName);
    return country ? country.frenchName : countryName;
}